# nixpacks.toml (Ajustado para Python 3.9)
[phases.setup]
# Usamos NixPkgs para incluir los paquetes base
nixPkgs = [
  "gdal",    
  "geos"
]

[phases.install]
# Usamos el comando de instalación estándar
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app --workers 1"
